- name: Install kubeadm, kubelet, and kubectl
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - kubeadm
    - kubelet
    - kubectl

- name: Initialize Kubernetes control plane
  command: kubeadm init --pod-network-cidr=10.244.0.0/16
  register: kubeadm_init

- name: Set up kubeconfig for the master
  shell: |
    mkdir -p $HOME/.kube
    cp /etc/kubernetes/admin.conf $HOME/.kube/config
    chown $(id -u):$(id -g) $HOME/.kube/config

- name: Generate join command
  shell: kubeadm token create --print-join-command
  register: join_command

- name: Save join command for workers
  set_fact:
    join_command: "{{ join_command.stdout }}"

- name: Install Flannel network plugin
  shell: kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml
