- name: Reset kubeadm
  shell: |
    export PATH=$PATH:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin && \
    sudo -E /usr/bin/kubeadm reset --force
  become: yes
  ignore_errors: yes


- name: remove .kube
  shell: |
    sudo rm -rf /home/ubuntu/.kube
  ignore_errors: yes

- name: Install kubeadm, kubelet, and kubectl
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - kubeadm
    - kubelet
    - kubectl
  become: yes

- name: Initialize Kubernetes control plane
  command: kubeadm init --pod-network-cidr={{ pod_network_cidr }}
  register: kubeadm_init_result
  retries: 5
  delay: 30
  until: kubeadm_init_result.rc == 0
  become: yes

- name: Save the join command
  shell: kubeadm token create --print-join-command
  register: join_command
  become: yes

- name: Create .kube directory and copy admin.conf
  shell: |
    sudo mkdir -p /root/.kube
    sudo cp /etc/kubernetes/admin.conf /root/.kube/config
  ignore_errors: yes


- name: Configure kubeconfig for kubectl (for the current user)
  shell: |
    sudo mkdir -p /home/ubuntu/.kube && echo "Directory created"
    sudo cp /etc/kubernetes/admin.conf /home/ubuntu/.kube/config && echo "File copied"
    sudo chown ubuntu:ubuntu /home/ubuntu/.kube/config && echo "Ownership changed"


- name: Deploy CNI Plugin (Flannel)
  command: kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml
  become: yes

