- name: Install kubeadm, kubelet, and kubectl
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - kubeadm
    - kubelet
    - kubectl
  become: yes

- name: Initialize Kubernetes control plane
  command: kubeadm init --pod-network-cidr={{ pod_network_cidr }}
  register: kubeadm_init_result
  retries: 5
  delay: 30
  until: kubeadm_init_result.rc == 0
  become: yes

- name: Save the join command
  shell: kubeadm token create --print-join-command
  register: join_command
  become: yes

- name: Create .kube directory and copy admin.conf
  shell: |
    sudo mkdir -p /root/.kube
    sudo cp /etc/kubernetes/admin.conf /root/.kube/config
  become: yes
  ignore_errors: yes


- name: Configure kubeconfig for kubectl (for the current user)
  shell: |
    sudo mkdir -p $HOME/.kube
    sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
    sudo chown $(id -u):$(id -g) $HOME/.kube/config
  environment:
    HOME: "{{ ansible_env.HOME }}"

- name: Deploy CNI Plugin (Flannel)
  command: kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml
  become: yes
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf
