- name: Install kubeadm, kubelet, and kubectl
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - kubeadm
    - kubelet
    - kubectl

- name: Initialize Kubernetes control plane
  command: kubeadm init --pod-network-cidr={{ pod_network_cidr }}
  register: kubeadm_init_result
  retries: 5
  delay: 30
  until: kubeadm_init_result.rc == 0

- name: Save the join command
  shell: kubeadm token create --print-join-command
  register: join_command

- name: Create .kube directory
  file:
    path: /root/.kube
    state: directory
    mode: '0755'

- name: Copy admin.conf to .kube
  copy:
    src: /etc/kubernetes/admin.conf
    dest: /root/.kube/config

- name: Deploy CNI Plugin (Flannel)
  command: kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml
