- name: Stop and disable kubelet service
  systemd:
    name: kubelet
    state: stopped
    enabled: no
  become: yes
  ignore_errors: yes

- name: Uninstall Kubernetes packages
  apt:
    name: kubeadm,kubelet,kubectl,kubernetes-cni
    state: absent
    purge: yes
  become: yes
  ignore_errors: yes

- name: Remove Kubernetes configuration files
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - /etc/kubernetes
    - /var/lib/kubelet
    - /var/lib/etcd
    - /var/lib/cni
    - /var/run/kubernetes
    - /etc/cni/net.d
  become: yes
  ignore_errors: yes

- name: Clean up iptables rules
  shell: iptables -F
  ignore_errors: yes
  become: yes
  ignore_errors: yes

- name: Remove Kubernetes repository and keys
  shell: |
    rm -rf /etc/apt/keyrings/kubernetes-apt-keyring.gpg
    rm -rf /etc/apt/sources.list.d/kubernetes.list
  ignore_errors: yes
  become: yes
  ignore_errors: yes

- name: Remove .kube directory
  file:
    path: /root/.kube
    state: absent
  become: yes
  ignore_errors: yes

- name: Stop containerd service
  systemd:
    name: containerd
    state: stopped
  become: yes
  ignore_errors: yes

- name: Disable containerd service
  systemd:
    name: containerd
    enabled: no
  become: yes
  ignore_errors: yes

- name: Remove containerd binary
  file:
    path: /usr/local/bin/containerd
    state: absent
  become: yes
  ignore_errors: yes

- name: Remove runc binary
  file:
    path: /usr/local/sbin/runc
    state: absent
  become: yes
  ignore_errors: yes

- name: Remove containerd directories
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - /etc/containerd
    - /var/lib/containerd
    - /run/containerd
    - /opt/cni/bin
  become: yes
  ignore_errors: yes

- name: Remove CNI plugins
  file:
    path: /opt/cni/bin
    state: absent
  become: yes
  ignore_errors: yes

- name: Remove containerd systemd service file
  file:
    path: /etc/systemd/system/containerd.service
    state: absent
  become: yes
  ignore_errors: yes

- name: Reload systemd daemon
  systemd:
    daemon_reload: yes
  become: yes
  ignore_errors: yes

- name: Update apt cache
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Disable swap
  shell: |
    swapoff -a
    sed -i '/swap/d' /etc/fstab

- name: Install dependencies
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg
    - software-properties-common

- name: Download containerd
  get_url:
    url: https://github.com/containerd/containerd/releases/download/v1.6.8/containerd-1.6.8-linux-amd64.tar.gz
    dest: /tmp/containerd-1.6.8-linux-amd64.tar.gz
  become: yes

- name: Unpack containerd
  unarchive:
    src: /tmp/containerd-1.6.8-linux-amd64.tar.gz
    dest: /usr/local
    remote_src: yes
  become: yes

- name: Download runc
  get_url:
    url: https://github.com/opencontainers/runc/releases/download/v1.1.3/runc.amd64
    dest: /tmp/runc.amd64
  become: yes

- name: Install runc
  command: sudo install -m 755 /tmp/runc.amd64 /usr/local/sbin/runc
  become: yes

- name: Download CNI plugins
  get_url:
    url: https://github.com/containernetworking/plugins/releases/download/v1.1.1/cni-plugins-linux-amd64-v1.1.1.tgz
    dest: /tmp/cni-plugins-linux-amd64-v1.1.1.tgz
  become: yes

- name: Create CNI bin directory
  file:
    path: /opt/cni/bin
    state: directory
  become: yes

- name: Unpack CNI plugins
  unarchive:
    src: /tmp/cni-plugins-linux-amd64-v1.1.1.tgz
    dest: /opt/cni/bin
    remote_src: yes
  become: yes

- name: Create containerd config directory
  file:
    path: /etc/containerd
    state: directory
  become: yes

- name: Create containerd default config
  shell: |
    containerd config default | sudo tee /etc/containerd/config.toml
  become: yes

- name: Enable SystemdCgroup
  replace:
    path: /etc/containerd/config.toml
    regexp: 'SystemdCgroup = false'
    replace: 'SystemdCgroup = true'
  become: yes

- name: Download containerd.service file
  get_url:
    url: https://raw.githubusercontent.com/containerd/containerd/main/containerd.service
    dest: /etc/systemd/system/containerd.service
  become: yes

- name: Reload systemd daemon
  systemd:
    daemon_reload: yes
  become: yes

- name: Enable and start containerd service
  systemd:
    name: containerd
    enabled: yes
    state: started
  become: yes

- name: Verify containerd service status
  command: sudo systemctl status containerd
  become: yes

- name: Fix ip_forward issue
  shell: |
    echo "net.ipv4.ip_forward=1" | sudo tee -a /etc/sysctl.d/99-sysctl.conf
    sudo sysctl -p
  become: yes

- name: Add Kubernetes package repository
  shell: |
    mkdir -p /etc/apt/keyrings
    curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.32/deb/Release.key | sudo gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg
    echo 'deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.32/deb/ /' | sudo tee /etc/apt/sources.list.d/kubernetes.list
  args:
    executable: /bin/bash

- name: Update apt package index
  apt:
    update_cache: yes
  