- name: Clean up previous Kubernetes configurations
  shell: |
    kubeadm reset -f || true
    rm -rf /etc/kubernetes
    iptables -F
  ignore_errors: yes

- name: Update apt cache
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Install dependencies
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg
    - software-properties-common

- name: Add Kubernetes package repository
  shell: |
    mkdir -p /etc/apt/keyrings
    curl -fsSL https://packages.cloud.google.com/apt/doc/apt-key.gpg | gpg --dearmor -o /etc/apt/keyrings/kubernetes-archive-keyring.gpg
    echo "deb [signed-by=/etc/apt/keyrings/kubernetes-archive-keyring.gpg] https://apt.kubernetes.io/ kubernetes-xenial main" > /etc/apt/sources.list.d/kubernetes.list
  args:
    executable: /bin/bash

- name: Disable swap
  shell: |
    swapoff -a
    sed -i '/swap/d' /etc/fstab

- name: Update apt package index
  apt:
    update_cache: yes
