- name: Clean up previous Kubernetes configurations
  shell: |
    kubeadm reset -f || true
    rm -rf /etc/kubernetes
    iptables -F
  ignore_errors: yes

- name: Update apt cache
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Disable swap
  shell: |
    swapoff -a
    sed -i '/swap/d' /etc/fstab

- name: Install dependencies
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg
    - software-properties-common

- name: Add Kubernetes package repository
  shell: |
    mkdir -p /etc/apt/keyrings
    curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.32/deb/Release.key | sudo gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg
    echo 'deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.32/deb/ /' | sudo tee /etc/apt/sources.list.d/kubernetes.list
  args:
    executable: /bin/bash

- name: Update apt package index
  apt:
    update_cache: yes
