- name: Wait for the worker node to be ready
  wait_for:
    host: "{{ inventory_hostname }}"
    port: 22
    timeout: 300
    state: started

- name: Install kubeadm, kubelet, and kubectl
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - kubeadm
    - kubelet
    - kubectl

- name: Join worker nodes to the cluster
  shell: "{{ hostvars['master']['join_command'] }}"
