- name: Install kubeadm, kubelet, and kubectl
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - kubeadm
    - kubelet
    - kubectl
  become: yes

- name: Wait for the master node to be ready
  wait_for:
    port: 6443
    host: "{{ groups['master'][0] }}"
    timeout: 300

- name: Join the worker node to the cluster
  command: "{{ hostvars[groups['master'][0]]['join_command'].stdout }}"
  retries: 5
  delay: 30
  register: join_result
  until: join_result.rc == 0
  become: yes
